version: '3.9'
services:

  nextjs:
    container_name: nextjs
    build: 
      context: phylogeny-lab
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    networks:
      - bridged_net_adapter

  postgres:
    container_name: postgresql
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridged_net_adapter

  fastapi:
    container_name: fastapi
    build:
      context: ./Backend
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend/app/data:/data
      - shared_tmp_volume:/filestore
    depends_on:
      - postgres
    networks:
      - bridged_net_adapter

  worker:
    container_name: worker
    restart: always
    build:
      context: ./Backend/app/worker
      dockerfile: worker.Dockerfile
    command: /code/app/worker/start-celery.sh
    volumes:
      - ./Backend/app/worker/logs/celery.log:/code/worker/logs/celery.log
      - shared_tmp_volume:/filestore
      - ncbi_databases:/volume/ncbi_databases
    env_file:
      - ./Backend/app/worker/.env
    ports:
      - 5556:5555
    depends_on:
      - redis
      - fastapi
    networks:
      - bridged_net_adapter

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - bridged_net_adapter

  minio:
    container_name: minio
    image: quay.io/minio/minio
    hostname: minio
    command: minio server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio:/data
    networks:
      - bridged_net_adapter

networks:
  bridged_net_adapter:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.50.0/24

volumes:
  redis_data:
  postgres_data:
  minio:
  shared_tmp_volume:
  ncbi_databases: