version: '3.9'
services:

  nextjs:
    container_name: nextjs
    build: 
      context: phylogeny-lab
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    networks:
      - bridged_net_adapter

  postgres:
    container_name: postgresql
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridged_net_adapter

  fastapi:
    container_name: fastapi
    build:
      context: ./Backend
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_URL=postgresql+asyncpg://admin:password@postgres/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/code/app/worker
      - MINIO_VOLUME=/volume
      - MINIO_BUCKET_NAME=minio-volume
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=password
      - MINIO_HOSTNAME=minio
    volumes:
      - ./Backend/app/data:/data
      - shared_tmp_volume:/tmp
    depends_on:
      - postgres
    networks:
      - bridged_net_adapter

  worker:
    container_name: worker
    restart: always
    build:
      context: ./Backend/app/worker
      dockerfile: worker.Dockerfile
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./Backend/app/worker/logs/celery.log:/code/worker/logs/celery.log
      - shared_tmp_volume:/tmp
      - ncbi_databases:/volume/ncbi_databases
    environment:
      - MINIO_VOLUME=/volume
      - MINIO_BUCKET_NAME=minio-volume
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=password
      - MINIO_HOSTNAME=minio
      - NCBI_DATABASE_DIR=/volume/ncbi_databases
      - API_ENDPOINT=http://fastapi:5000/api
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_URL=postgresql+asyncpg://admin:password@postgres/postgres
    depends_on:
      - redis
      - fastapi
    networks:
      - bridged_net_adapter

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - bridged_net_adapter

  flower:
    container_name: flower
    build: 
      context: ./Backend/app/worker
      dockerfile: flower.Dockerfile
    command: ./start-flower.sh
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_UNAUTHENTICATED_API=true
      - MINIO_VOLUME=/volume
      - MINIO_BUCKET_NAME=minio-volume
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=password
      - MINIO_HOSTNAME=minio
    volumes:
      - flower_data:/data
    depends_on:
      - fastapi
      - redis
      - worker
    networks:
      - bridged_net_adapter

  minio:
    container_name: minio
    image: quay.io/minio/minio
    hostname: minio
    command: minio server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio:/data
    networks:
      - bridged_net_adapter

networks:
  bridged_net_adapter:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.50.0/24

volumes:
  flower_data:
  redis_data:
  postgres_data:
  minio:
  shared_tmp_volume:
  ncbi_databases: