version: '3.9'
services:

  nextjs:
    container_name: nextjs
    build: 
      context: phylogeny-lab
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    networks:
      - bridged_net_adapter

  postgres:
    container_name: postgresql
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/volume:/var/lib/postgresql/data
    networks:
      - bridged_net_adapter

  fastapi:
    container_name: fastapi
    build:
      context: ./Backend
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_URL=postgresql://admin:password@postgres/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/code/app/Blast_server
    depends_on:
      - postgres
      - redis
    networks:
      - bridged_net_adapter

  blast_server:
    container_name: blast_server
    build:
      context: ./Backend/app/Blast_server
      dockerfile: Dockerfile
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./Backend/app/Blast_server:/usr/src/app
      - ./Backend/app/Blast_server/logs/celery.log:/code/Blast_server/logs/celery.log
      - ./Backend/app/Blast_server/volume:/volume
    environment:
      - BLAST_SAVE_DIR=/volume/blast_queries
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - fastapi
      - redis
    networks:
      - bridged_net_adapter

  redis:
    container_name: redis
    image: redis:7
    networks:
      - bridged_net_adapter

  dashboard:
    container_name: flower_dashboard
    build: 
      context: ./Backend/app/Blast_server
      dockerfile: Dockerfile
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - fastapi
      - redis
      - blast_server
    networks:
      - bridged_net_adapter

networks:
  bridged_net_adapter:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.50.0/24